// Configuração do Supabase
export const supabaseConfig = {
  url: 'https://nudqbqtaoabkbhlwttuii.supabase.co',
  key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51ZHFicXRhb2Fia2JobHd0dWlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxODkwODYsImV4cCI6MjA3Mjc2NTA4Nn0.hLYM7P19NvSAY6mNHdQNp2EEnQKTENBwmeEV4WAzBpk',
  serviceKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51ZHFicXRhb2Fia2JobHd0dWlpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzE4OTA4NiwiZXhwIjoyMDcyNzY1MDg2fQ.xBheWozakNvfrGnP-MSLwMQhqIl6A3zu--ZYeydFjKg'
};

export default supabaseConfig;